version: '3.8'
services:
  app:
    image: bellsoft/liberica-openjre-alpine-musl:11.0.19
    restart: on-failure
    command:
      - java
      - "-DtinkoffInvestApi.token=${TINKOFF_TOKEN}"
      - "-Dslick.db.properties.serverName=${POSTGRES_HOST}"
      - "-Dslick.db.properties.portNumber=${POSTGRES_PORT}"
      - "-Dslick.db.properties.databaseName=${POSTGRES_DBNAME}"
      - "-Dslick.db.properties.user=${POSTGRES_USER}"
      - "-Dslick.db.properties.password=${POSTGRES_PASSWORD}"
      - -cp
      - jars/app.jar
      - ru.mikhaildruzhinin.trader.Trader
    volumes:
      - ./jars:/jars
