version: '3.8'
services:
  app:
    depends_on:
      - db
    command:
      - java
      - "-DtinkoffInvestApi.token=${TINKOFF_TOKEN}"
      - "-Dslick.db.properties.serverName=${POSTGRES_HOST}"
      - "-Dslick.db.properties.portNumber=${POSTGRES_PORT}"
      - "-Dslick.db.properties.databaseName=${POSTGRES_DBNAME}"
      - "-Dslick.db.properties.user=${POSTGRES_USER}"
      - "-Dslick.db.properties.password=${POSTGRES_PASSWORD}"
      - -cp
      - jars/trader-assembly-0.1.0-SNAPSHOT.jar
      - ru.mikhaildruzhinin.trader.Trader
    volumes:
      - ./target/scala-2.13:/jars
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '2345:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/scripts.sql
